@startuml
!pragma teoz true
'Issue #656
A -> B++: Get data
& A -> C++:
& A -> D++:
B -->> A--: Data
& C -->> A--:
& D -->> A--:
@enduml
@startuml
!pragma teoz true
'Issue #739 & Forum 14873
autonumber
AAA -> BBB++: Message 0
BBB -[#22A722]> DDD: Message 1
deactivate BBB
activate DDD
& DDD -> EEE: Message 2
note right #red: <-- Expect 1 & 2 to be same row
DDD -[#22A722]> FFF++--: Msg 3
& FFF -> GGG--: Msg 4
note right #red: <-- Expect 3 & 4 to be same row
@enduml
@startuml
!pragma teoz true
'Issue #1094
== Bad I ==
A -> B ++		: ping
note right: Lifeline extends\n past message
B -->? : log
& B -> A --		: pong
== Bad II ==
A -> B 			: ping
Activate B
note right: equally broken\nwithout --/++ notation
B -->? : log
& B -> A 		: pong
Deactivate B
== Good ==
A -> B ++		: ping
note right: but not perfect:\n"log" too close\n to lifeline
B -> A --		: pong
& B -->? : log
== Best ==
A -> B 			: ping
Activate B
note right: Looks perfect!
B -->? : log
Deactivate B
& B -> A 		: pong
@enduml
@startuml
!pragma teoz true
'Forum 13409
activate b
b -> a --++ #red : hello
deactivate a
b -> a : hello2
activate a #green
deactivate a
b -> a ++ #green: hello3
@enduml
@startuml
!pragma teoz true
' Forum 12899 -- requested slight stepping though.
autoactivate on

participant Alice
box "Grouping" #LightBlue
 participant Bob
 participant Charlie
end box
participant Dave

  Alice -> Bob : request
&  Bob -> Charlie : request
&   Charlie -> Dave : request
    Charlie <-- Dave : response
&  Bob <-- Charlie : response
& Alice <-- Bob : response
@enduml
@startuml
!pragma teoz true
'Issue 1099
  A <[#red]-o? ++
  A -> B -- : very long\nmulti-line
& B -> C ++ #red: single
note over C: got it
Deactivate C
====
  A <-o? ++ #green
  A -> B -- : very long\nmulti-line
& B -> C ++ #green : same\nheight
note over C: got it
Deactivate C
====
  A <-o? ++ #red
  'activate A
  A -> B -- : single
& B -> C ++ : very long\nmulti-line
note over C: got it
Deactivate C
@enduml
@startuml
!pragma teoz true
'Issue #1494
'skinparam style strictuml

Actor Mallory as m
Actor Bob as b
Actor Alice as a

activate b
b ->> a --++ : Hi Alice!
a ->> b --++ : Bye Bob!

b ->> a ++ : Bye Alice!
& b ->> m --++ : Bye Alice!

deactivate a
deactivate m
@enduml
@startuml
!pragma teoz true
'Issue #1723
dummy -> A ++: first step

A -> A: test
A -> B --++: second step

B -> B: test
B -> C--: third step

@enduml
@startuml
!pragma teoz true
note over Bob, Alice: teoz true
activate Bob
Bob -> Alice ++--: not ok
Alice-> Alice: style 1
deactivate Alice

activate Bob
Bob -> Alice ++: not ok
deactivate Bob
Alice -> Alice: style 1
deactivate Alice

activate Bob
Bob -> Alice: not ok
deactivate Bob
activate Alice
Alice -> Alice: style 1
deactivate Alice

activate Bob
Bob -> Alice --: not ok
activate Alice
Alice -> Alice: style 2
deactivate Alice
@enduml
@startuml
!pragma teoz true
'also Forum 15191
Bob -> Alice : message
& note right of Alice: ok
Alice -[hidden]> Alice

activate Bob
Bob -> Alice --: deactivate
& note right of Alice: ok

Bob -> Alice ++: activate
& note right of Alice: ok
deactivate Alice

activate Bob
Bob -> Alice --++: act+deact
& note right of Alice: not ok
deactivate Alice
@enduml
@startuml
!pragma teoz true
'Issue #1494 with additional parallel to C.
'skinparam style strictuml

Actor Mallory as m
Actor Bob as b
Actor Alice as a
Actor Charlie as c

activate b
b ->> a --++ : Hi Alice!
a ->> b --++ : Bye Bob!

b ->> a ++ : Bye Alice!
& b ->> m ++ : Bye Alice!
& a ->> c ++: Bye C too!
deactivate b

deactivate a
deactivate m
deactivate c
@enduml

@startuml
'Forum 16663
!pragma teoz true
First -> Second : message
activate First
activate Second
Second ->  First: response
deactivate First
deactivate Second
@enduml


@startuml
!pragma teoz true
'Forum 14803
actor Alice
actor Bob
actor Charlie
actor Dave
Bob -> Alice ++: message1
Alice -> Bob & Dave & Charlie --++: multicast message
@enduml

@startuml
!pragma teoz true
'Issue #656 -- modified
A -> B++: Get data
& B -> C++:a\n2
& C -> D++:
B -->> A--: Data
& C -->> A--:
& D -->> C--:a\n2
@enduml

@startuml
!pragma teoz true
A -> B++: Get data
& B -> C++:a\n2
& C -> D++:
D -->> C--:a\n2
& C -->> A--:
&B -->> A--: Data


@enduml

@startuml
!pragma teoz true
'Issue #656
A -> B++: Get data
& B -> C++:a\n2
& C -> D++: a\n2\n3
@enduml

@startuml
!pragma teoz true

group #ffa Group 1
    Particpant_A -> Particpant_B
    activate Particpant_A
    Particpant_A <- Particpant_B
    deactivate Particpant_A
end

group #ffa Group 2
    Particpant_A -> Particpant_B++
    Particpant_A <- Particpant_B--
end

group #ffa Group 3
    Particpant_A -> Particpant_B++
    activate Particpant_A
    Particpant_A <- Particpant_B--
    deactivate Particpant_A
end

group #ffa Group 4
    Particpant_A -> Particpant_B
    Particpant_A <- Particpant_B
end
@enduml

@startuml
!pragma teoz true

browser -> ssl_server.exe : 1
browser -> ssl_server.exe : 2
browser -> ssl_server.exe : 3
browser -> ssl_server.exe : 4
browser -> ssl_server.exe : 5


group SSL Application data
browser -> ssl_server.exe : in
end /' SSL Application data '/


destroy browser

@enduml

@startuml
'!pragma teoz true
title no teoz
group #ffa Group 1
    Particpant_A -> Particpant_B
    activate Particpant_A
    Particpant_A <- Particpant_B
    deactivate Particpant_A
end

group #ffa Group 2
    Particpant_A -> Particpant_B++
    Particpant_A <- Particpant_B--
end

group #ffa Group 3
    Particpant_A -> Particpant_B++
    activate Particpant_A
    Particpant_A <- Particpant_B--
    deactivate Particpant_A
end

group #ffa Group 4
    Particpant_A -> Particpant_B
    Particpant_A <- Particpant_B
end

group #ffa Group 5, Which has a very long header
    Particpant_A -> Particpant_B++
    activate Particpant_A
    Particpant_A <- Particpant_B--
    deactivate Particpant_A
end

group #ffa Group 6, While also has a very long header
    Particpant_A -> Particpant_B
    Particpant_A <- Particpant_B
end
@enduml

@startuml
skinparam {
      Maxmessagesize 200
   }

   group Grouping messages
      Test <<-- Test : The group frame does not draw a border around the text (located on the left side), but ignores its presence, and also ignores the presence of a line.
   end
@enduml

@startuml
group
    a -> a : This works fine
end
group
    a <- a : This does not work
end
@enduml