@startuml
component A
component B
component C
component D

A -up-> B : > up arrow [not] **missing**
B <-down- A : < up arrow works
B -right-> C : > right arrow works
C -down-> D : > down arrow works
D -left-> A : > left arrow [not] **missing**
A <-right- D : < left arrow works

@enduml
