@startuml
!pragma teoz true
'Issue #1494 with additional parallel to C.
'skinparam style strictuml

'Actor Bob as b
'Actor Alice as a
'Actor Charlie as c

activate b
'b ->> a --++ : Hi Alice!
'a ->> b --++ : Bye Bob!

b ->> a --++: Bye Alice!
'& b ->> m ++ : Bye Alice!
 & opt test
 a ->> c  : Bye C too!
 activate c
 end
 @enduml