@startuml
!pragma teoz true
skinparam ParticipantPadding 20
Activate A #green
'||8|| /' work-around #2 '/
...Bug 2: Already\n activated doesn't show...
A ->] : +1
Deactivate A

== Cleanse, Repeat==

'B <[#red]-? : Bug 1: Need spurious arrow
Activate A #green
'||8|| /' work-around #2 '/
... See Bug 2 above ...
A ->] : +1
Deactivate A
@endnuml